# Generated by Django 5.2.4 on 2025-07-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_message_options_alter_message_receipient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('sender', 'receipient')},
        ),
    ]
