# Generated by Django 5.2.4 on 2025-07-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_message_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('sender', models.F('receipient')), _negated=True), name='prevent_self_message'),
        ),
    ]
