# Generated by Django 5.2.4 on 2025-07-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_message_prevent_self_message'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='prevent_self_message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receipient',
            new_name='recipient',
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('sender', models.F('recipient')), _negated=True), name='prevent_self_message'),
        ),
    ]
