# Generated by Django 6.0.4 on 2026-04-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_message_prevent_self_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signup_method',
            field=models.CharField(blank=True, default='email', max_length=50, null=True),
        ),
    ]
