# Generated by Django 6.0.4 on 2026-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_signup_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
