# Generated by Django 6.0.4 on 2026-06-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.jpg', upload_to='profiles/'),
        ),
    ]
