# Generated by Django 5.2.4 on 2025-07-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_vote_count_project_vote_ratio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='github_link',
            new_name='source_link',
        ),
    ]
