# Generated by Django 6.0.4 on 2026-06-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default_project.jpg', null=True, upload_to='projects/'),
        ),
    ]
