services:
  - type: web
    name: devsearch
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn devsearch.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: devsearch.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: SITE_URL
        value: https://your-app.onrender.com
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_USER
        value: your-email@example.com
      - key: EMAIL_PASSWORD
        value: your-app-password
      - key: EMAIL_PORT
        value: "587"
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false

  - type: worker
    name: devsearch-mailer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runmailer
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: devsearch.settings.prod
      - key: SECRET_KEY
        sync: false
