services:
  - type: web
    name: devsearch
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn devsearch.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: devsearch.settings.prod
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DEV_EMAIL_USER
        value: "demo@example.com"
      - key: DEV_EMAIL_PASSWORD
        value: "dummypassword"
      - key: DATABASE_URL
        fromDatabase:
          name: devsearch-db
          property: connectionString

databases:
  - name: devsearch-db
    databaseName: devsearch
    plan: free
